#!/bin/sh

config_name="sblite"

touch /etc/config/$config_name

section_type="sing_box"
uci set $config_name.main=$section_type
uci set $config_name.access_control=$section_type
uci set $config_name.route=$section_type
uci set $config_name.dns=$section_type
uci set $config_name.subscribe=$section_type

uci commit

/etc/init.d/rpcd reload
exit 0
