#!/bin/sh /etc/rc.common

USE_PROCD=1

START=99
STOP=15

CONFIG=sblite
$APP_FILE=/usr/share/${CONFIG}/app.sh

start_service() {
    procd_open_instance $CONFIG
    procd_set_param command $APP_FILE start && sing-box run -c /tmp/sblite/config.json
    procd_set_param user root
    procd_set_param limits core="unlimited"
    procd_set_param limits nofile="1000000 1000000"
    procd_set_param stdout 1
    procd_set_param stderr 1

    procd_set_param pidfile /var/run/${CONFIG}.pid

    procd_close_instance
}
